x_knockoff  = \(x, monte = 50, seed = 42) {
  set.seed(seed)

  cor.G = stats::cor(x)
  n.sample = nrow(x)
  n.G = ncol(x)
  x.knockoff = array(NA, dim = c(n.sample, n.G, monte),
                     dimnames = list(rownames(x), colnames(x), 1:monte))

  knockoff = GhostKnockoff.prelim(cor.G, M = monte, method = "asdp")
  P.each = knockoff$P.each
  V.left = as.matrix(knockoff$V.left)
  permute.index = knockoff$permute.index
  permute.V.index = rep(permute.index, monte)

  Normal_50Studies = as.matrix(V.left %*% matrix(stats::rnorm(ncol(V.left) * n.sample), ncol(V.left), n.sample))  # 50 -> sample size
  Normal_50Studies[permute.V.index == 1, ] = matrix(
    stats::rnorm(sum(permute.index) * monte * n.sample), sum(permute.index) * monte, n.sample)

  for (i in seq_len(n.sample)) {
    Normal_k = matrix(Normal_50Studies[, i], nrow = n.G)
    x_ik = as.vector(P.each %*% t(x[i, , drop = F])) + Normal_k
    for (j in seq_len(monte)) {
      x.knockoff[i,,j] = x_ik[,j]
    }
  }

  return(x.knockoff)
}

#' Title
#'
#' @inheritParams infoxtr::surd
#' @param data Observation data. Must be dataframe or matrix.
#' @param monte (optional) Number of Monte Carlo sample generated by knockoff operation.
#' @param seed (optional) Random seed used for Monte Carlo knockoff sample generation.
#'
#' @returns A matrix.
#' @export
#'
#' @examples
#' set.seed(42)
#' z = stats::rnorm(100)
#' x = sin(z) + 0.01 * stats::rnorm(100)
#' y = sin(x) + exp(z) + 0.01 * stats::rnorm(100)
#' data = cbind(x, y, z)
#' kocmi::construct_knockoff(data, 1, 1:3)
#'
construct_knockoff = \(data, target, agent, monte = 50, seed = 42){
  k.array = x_knockoff(data[,c(target,agent),drop = FALSE], monte, seed)
  return(apply(k.array, 3, \(.x) .x[,1]))
}
