#' Knockoff Conditional Mutual Information Test for Single Variable Pair
#'
#' Tests the statistical significance of conditional mutual information between
#' a single regulator (agent) variable and a target variable, controlling for
#' conditioning variables using knockoff-based virtual intervention.
#'
#' @inheritParams infoxtr::kocmi
#' @param regulator Integer vector of column indices for the regulator variable.
#' @param monte (optional) Number of Monte Carlo sample generated by knockoff operation.
#' @param contain_null (optional) Logical. If `TRUE`, the test statistic is
#'   computed using knockoffs generated under the null model. In this case
#'   the difference is defined as \eqn{I(Y; X_{null} | Z) - I(Y; X_{knockoff} | Z)}.
#'   If `FALSE`, the original conditional mutual information \eqn{I(Y; X | Z)} is
#'   used instead and compared against the knockoff estimates \eqn{I(Y; X_{knockoff} | Z)}.
#'
#' @returns A named numeric vector.
#' @export
#'
#' @examples
#' set.seed(42)
#' beta = 0.01
#' z = stats::rnorm(100)
#' x = sin(z) + beta * stats::rnorm(100)
#' y = sin(x) + exp(z) + beta * stats::rnorm(100)
#' data = cbind(x, y, z)
#' kocmi::kocmi_single(data, 1, 2, 3)
#'
kocmi_single = \(data, target, regulator, conds, type = c("cont", "disc"),
                 monte = 40, nboots = 1e4, k = 3, threads = 1, seed = 42,
                 base = exp(1), method = "equal", contain_null = TRUE) {
  type = match.arg(type)
  mat = infoxtr:::.convert2mat(data, type)
  knockoff = construct_knockoff(mat, regulator, conds, monte, seed)
  null_knockoff = NULL
  if (contain_null) {
    null_knockoff = construct_knockoff(mat, regulator, c(target,conds), monte, seed)
  }
  return(infoxtr:::RcppKOCMI(
            mat, target, regulator, conds, knockoff, null_knockoff, type,
            nboots, k, 0, threads, seed, base, method, contain_null))
}

kocmi_net = \(data, vars, type = c("cont", "disc"), monte = 40, nboots = 1e4, k = 3,
              threads = 1, seed = 42, base = exp(1), method = "equal", contain_null = TRUE) {
  type = match.arg(type)
  mat = infoxtr:::.convert2mat(data[,vars,drop = FALSE], type)
  new_vars = seq_along(vars)
  knockoff = construct_knockoff(mat, regulator, conds, monte, seed)
  null_knockoff = NULL
  if (contain_null) {
    null_knockoff = x_knockoff(mat, monte, seed)
  }
  return(infoxtr:::RcppKOCMI(
    mat, target, regulator, conds, knockoff, null_knockoff, type,
    nboots, k, 0, threads, seed, base, method, contain_null))
}
