#' Knockoff Conditional Mutual Information Test for Single Variable Pair
#'
#' @inheritParams infoxtr::kocmi
#' @param regulator Integer vector of column indices for the regulator variable.
#' @param monte (optional) Number of Monte Carlo sample generated by knockoff operation.
#' @param contain_null (optional) Logical. If `TRUE`, the test statistic is
#'   computed using knockoffs generated under the null model. In this case
#'   the difference is defined as \eqn{I(Y; X_{null} | Z) - I(Y; X_{knockoff} | Z)}.
#'   If `FALSE`, the original conditional mutual information \eqn{I(Y; X | Z)} is
#'   used instead and compared against the knockoff estimates \eqn{I(Y; X_{knockoff} | Z)}.
#'
#' @returns A named numeric vector.
#' @export
#'
#' @examples
#' set.seed(42)
#' z = stats::rnorm(100)
#' x = sin(z) + 0.01 * stats::rnorm(100)
#' y = sin(x) + exp(z) + 0.01 * stats::rnorm(100)
#' data = cbind(x, y, z)
#' kocmi::kocmi_single(data, 1, 2, 3)
#'
kocmi_single = \(data, target, regulator, conds, type = c("cont", "disc"),
                 monte = 40, nboots = 1e4, k = 3, threads = 1, seed = 42,
                 base = exp(1), method = "equal", contain_null = TRUE) {
  type = match.arg(type)
  mat = infoxtr:::.convert2mat(data, type)

  knockoff = construct_ghostknockoff(mat, regulator, conds, monte, seed)

  null_knockoff = NULL
  if (contain_null) {
    null_knockoff = construct_ghostknockoff(mat, regulator, c(target,conds), monte, seed)
  }

  return(infoxtr:::RcppKOCMI(
            mat, target, regulator, conds, knockoff, null_knockoff, type,
            nboots, k, 0, threads, seed, base, method, contain_null))
}

#' Knockoff Conditional Mutual Information Test for Selected Variables
#'
#' @inheritParams kocmi_single
#' @param vars Integer vector of column indices to include in kocmi calculation.
#'
#' @returns A dataframe.
#' @export
#'
#' @examples
#' set.seed(42)
#' z = stats::rnorm(100)
#' x = sin(z) + 0.01 * stats::rnorm(100)
#' y = sin(x) + exp(z) + 0.01 * stats::rnorm(100)
#' data = cbind(x, y, z)
#' kocmi::kocmi_net(data, 1:3)
#'
kocmi_net = \(data, vars, type = c("cont", "disc"), monte = 40, nboots = 1e4, k = 3,
              threads = 1, seed = 42, base = exp(1), method = "equal", contain_null = TRUE) {
  type = match.arg(type)
  vars = sort(unique(vars))
  mat = infoxtr:::.convert2mat(data, type)[,vars,drop = FALSE]

  null_knockoff = NULL
  if (contain_null) {
    null_knockoff = kocmi::x_ghostknockoff(mat, monte, seed)
  }

  new_vars = seq_along(vars)
  var_pairs = utils::combn(new_vars, 2, simplify = FALSE)
  tvi = vector("integer", length(var_pairs)*2)
  rvi = vector("integer", length(var_pairs)*2)
  tv = vector("double", length(var_pairs)*2)
  pv = vector("double", length(var_pairs)*2)

  doclust = FALSE
  if (threads > 1) {
    doclust = TRUE
    cl = parallel::makeCluster(threads)
    on.exit(parallel::stopCluster(cl), add = TRUE)
  }

  run_single_node = \(i) {
    vp = var_pairs[[i]]
    conds = setdiff(new_vars, vp)

    vp_null_knockoff = NULL
    vp_knockoff = kocmi::construct_ghostknockoff(mat, vp[1], conds, monte, seed)
    if (contain_null) vp_null_knockoff = apply(null_knockoff, 3, \(.x) .x[,vp[1]])
    cs12 = infoxtr:::RcppKOCMI(
      mat, vp[2], vp[1], conds, vp_knockoff, vp_null_knockoff,
      type, nboots, k, 0, 1, seed, base, method, contain_null)
    tvi[i] = vars[vp[2]]; rvi[i] = vars[vp[1]]
    tv[i] = cs12[1]; pv[i] = cs12[2]

    vp_knockoff = kocmi::construct_ghostknockoff(mat, vp[2], conds, monte, seed)
    if (contain_null) vp_null_knockoff = apply(null_knockoff, 3, \(.x) .x[,vp[2]])
    cs21 = infoxtr:::RcppKOCMI(
      mat, vp[1], vp[2], conds, vp_knockoff, vp_null_knockoff,
      type, nboots, k, 0, 1, seed, base, method, contain_null)
    tvi[i + length(var_pairs)] = vars[vp[1]]
    rvi[i + length(var_pairs)] = vars[vp[2]]
    tv[i + length(var_pairs)] = cs21[1]
    pv[i + length(var_pairs)] = cs21[2]

    return(i) # Just return as a marker of finishing
  }

  if (doclust) {
    out_res = parallel::parLapply(cl, seq_along(var_pairs), run_single_node)
  } else {
    for (i in seq_along(var_pairs)) run_single_node(i)
  }

  return(data.frame(
    regulator = rvi, target = tvi,
    cs = abs(tv), t_stat = tv, p_value = pv,
    p_adj = stats::p.adjust(pv,method = "BH")
  ))
}
