#' Knockoff Conditional Mutual Information Test for Single Variable Pair
#'
#' Tests the statistical significance of conditional mutual information between
#' a single regulator (agent) variable and a target variable, controlling for
#' conditioning variables using knockoff-based virtual intervention.
#'
#' @inheritParams infoxtr::kocmi
#' @param regulator Integer vector of column indices for the regulator variable.
#' @param monte (optional) Number of Monte Carlo sample generated by knockoff operation.
#' @param contain_null (optional) Logical. If `TRUE`, the test statistic is
#'   computed using knockoffs generated under the null model. In this case
#'   the difference is defined as \eqn{I(Y; X_{null} | Z) - I(Y; X_{knockoff} | Z)}.
#'   If `FALSE`, the original conditional mutual information \eqn{I(Y; X | Z)} is
#'   used instead and compared against the knockoff estimates \eqn{I(Y; X_{knockoff} | Z)}.
#'
#' @returns A named numeric vector.
#' @export
#'
#' @examples
#' set.seed(42)
#' beta = 0.01
#' z = stats::rnorm(100)
#' x = sin(z) + beta * stats::rnorm(100)
#' y = sin(x) + exp(z) + beta * stats::rnorm(100)
#' data = cbind(x, y, z)
#' kocmi::kocmi_single(data, 1, 2, 3)
#'
kocmi_single = \(data, target, regulator, conds, type = c("cont", "disc"),
                 monte = 40, nboots = 1e4, k = 3, threads = 1, seed = 42,
                 base = exp(1), method = "equal", contain_null = TRUE) {
  type = match.arg(type)
  mat = infoxtr:::.convert2mat(data, type)

  knockoff = construct_knockoff(mat, regulator, conds, monte, seed)

  null_knockoff = NULL
  if (contain_null) {
    null_knockoff = construct_knockoff(mat, regulator, c(target,conds), monte, seed)
  }

  return(infoxtr:::RcppKOCMI(
            mat, target, regulator, conds, knockoff, null_knockoff, type,
            nboots, k, 0, threads, seed, base, method, contain_null))
}

kocmi_net = \(data, vars, type = c("cont", "disc"), monte = 40, nboots = 1e4, k = 3, threads = 1,
              seed = 42, base = exp(1), method = "equal", contain_null = TRUE, verbose = FALSE) {
  type = match.arg(type)
  vars = sort(unique(vars))
  mat = infoxtr:::.convert2mat(data[,vars,drop = FALSE], type)

  null_knockoff = NULL
  if (contain_null) {
    null_knockoff = x_knockoff(mat, monte, seed)
  }

  new_vars = seq_along(vars)
  var_pairs = utils::combn(new_vars, 2, simplify = FALSE)
  tvi = vector("integer", length(var_pairs)*2)
  rvi = vector("integer", length(var_pairs)*2)
  tv = vector("double", length(var_pairs)*2)
  pv = vector("double", length(var_pairs)*2)
  if (verbose) txtpb = utils::txtProgressBar(min = 1, max = length(var_pairs))
  for (i in seq_along(var_pairs)) {
    vp = var_pairs[[i]]
    conds = setdiff(new_vars, vp)

    vp_knockoff = construct_knockoff(mat, vp[1], conds, monte, seed)
    if (contain_null) vp_null_knockoff = apply(null_knockoff, 3, \(.x) .x[,vp[1]])
    cs12 = infoxtr:::RcppKOCMI(
      mat, vp[2], vp[1], conds, vp_knockoff, vp_null_knockoff, type,
      nboots, k, 0, threads, seed, base, method, contain_null)
    tvi[i + length(var_pairs)] = vars[vp[2]]
    rvi[i + length(var_pairs)] = vars[vp[1]]
    tv[i + length(var_pairs)] = cs12[1]
    pv[i + length(var_pairs)] = cs12[2]

    vp_knockoff = construct_knockoff(mat, vp[2], conds, monte, seed)
    if (contain_null) vp_null_knockoff = apply(null_knockoff, 3, \(.x) .x[,vp[2]])
    cs21 = infoxtr:::RcppKOCMI(
      mat, vp[1], vp[2], conds, vp_knockoff, vp_null_knockoff, type,
      nboots, k, 0, threads, seed, base, method, contain_null)
    tvi[i] = vars[vp[1]]; rvi[i] = vars[vp[2]]
    tv[i] = cs21[1]; pv[i] = cs21[2]

    if (verbose) utils::setTxtProgressBar(txtpb, i)
  }
  if (verbose) close(txtpb)

  return(data.frame(
    regulator = rvi, target = tvi,
    cs = abs(tv), t_stat = tv, p_value = pv,
    p_adj = stats::p.adjust(pv,method = "BH")
  ))
}
